// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMEKkC58VWI6CTzko-U3T8Mkp-1jNWHCA',
    appId: '1:1069211223885:web:07296692edc6268edcd904',
    messagingSenderId: '1069211223885',
    projectId: 'shree-balaji-4666c',
    authDomain: 'shree-balaji-4666c.firebaseapp.com',
    storageBucket: 'shree-balaji-4666c.firebasestorage.app',
    measurementId: 'G-E9PSXJB1EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmB_Y3-eJSU_bRouc31akiptJ924TYHoQ',
    appId: '1:1069211223885:android:4b960621eb244981dcd904',
    messagingSenderId: '1069211223885',
    projectId: 'shree-balaji-4666c',
    storageBucket: 'shree-balaji-4666c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp07vh4JWBEg9Zu7krEKXHoN3d7CX1814',
    appId: '1:1069211223885:ios:8cdf2e03b2a0ad40dcd904',
    messagingSenderId: '1069211223885',
    projectId: 'shree-balaji-4666c',
    storageBucket: 'shree-balaji-4666c.firebasestorage.app',
    iosBundleId: 'com.sbt.sbt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp07vh4JWBEg9Zu7krEKXHoN3d7CX1814',
    appId: '1:1069211223885:ios:265a401e94c31fdadcd904',
    messagingSenderId: '1069211223885',
    projectId: 'shree-balaji-4666c',
    storageBucket: 'shree-balaji-4666c.firebasestorage.app',
    iosBundleId: 'com.visiondgtech.shreebalajitunch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMEKkC58VWI6CTzko-U3T8Mkp-1jNWHCA',
    appId: '1:1069211223885:web:a8964ed3c9959ed4dcd904',
    messagingSenderId: '1069211223885',
    projectId: 'shree-balaji-4666c',
    authDomain: 'shree-balaji-4666c.firebaseapp.com',
    storageBucket: 'shree-balaji-4666c.firebasestorage.app',
    measurementId: 'G-VMLZRX8GVT',
  );
}
